version: '3'
services:

  #PHP
  carasv2:
    image: fedemramato/laravel-php7.3:latest
    container_name: carasv2-site
    environment:
      VIRTUAL_HOST: dev-new-caras.perfil.com
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./:/var/www/html
      - /var/nfsperfil:/var/www/nfs
    networks:
      - webapps-network

#Network
networks:
  webapps-network:
    external:
      name: webapps-network

#Volumes
volumes:
  dbdata:
    driver: local
